sonar.host.url=https://sonarcloud.io
sonar.projectKey=user-app-aws
sonar.organization=gowdamanju


sonar.modules=User-Service,cdk-infra

sonar.sourceEncoding=UTF-8

sonar.exclusions=cdk-infra/**,**/cdk-infra/**
#sonar.scm.exclusions.disabled=true